#copied from https://jekyllrb.com/docs/continuous-integration/

language: ruby
rvm:
- 2.1

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./ci-build.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
