# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simon Ramsay
email: simon@ramsay.xyz
description: "A personal blog about shitty infrequent random programing tips"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ramsay.xyz" # the base hostname & protocol for your site
github_username:  "nexus-uw"
gpg_key_finger_print: "F50F7E3612EA2B78"
keybase_username: "nexusuw"

# Build settings
markdown: kramdown

exclude: [vendor]
plugins: [jekyll-paginate]
paginate: 15
